"""MCP tool definitions for Qlik measure retrieval"""

import re
from datetime import datetime
from typing import Annotated, Any

from pydantic import BaseModel, Field, field_validator

from .qlik_client import QlikClient


class GetAppMeasuresArgs(BaseModel):
    """Retrieve all measures from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    creates a MeasureList session object, retrieves all measure metadata,
    and returns the results as structured JSON.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    include_expression: Annotated[bool, Field(
        default=True,
        description="Include measure expressions in the response. Set to False for lighter payload.",
    )] = True
    include_tags: Annotated[bool, Field(
        default=True,
        description="Include measure tags in the response. Tags help categorize and organize measures.",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


class GetAppVariablesArgs(BaseModel):
    """Retrieve all variables from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    creates a VariableList session object, retrieves all variable metadata,
    and returns the results as structured JSON.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    include_definition: Annotated[bool, Field(
        default=True,
        description="Include variable definitions/expressions in the response.",
    )] = True
    include_tags: Annotated[bool, Field(
        default=True,
        description="Include variable tags for categorization.",
    )] = True
    show_reserved: Annotated[bool, Field(
        default=True,
        description="Include reserved system variables (e.g., system-generated variables).",
    )] = True
    show_config: Annotated[bool, Field(
        default=True,
        description="Include configuration variables used for app settings.",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


class GetAppFieldsArgs(BaseModel):
    """Retrieve all fields and table information from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    creates a FieldList session object, retrieves all field metadata and table information,
    and returns the results as structured JSON for data model analysis.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    show_system: Annotated[bool, Field(
        default=True,
        description="Include system fields (automatically generated by Qlik).",
    )] = True
    show_hidden: Annotated[bool, Field(
        default=True,
        description="Include hidden fields marked with HidePrefix/HideSuffix.",
    )] = True
    show_derived_fields: Annotated[bool, Field(
        default=True,
        description="Include derived fields created through expressions.",
    )] = True
    show_semantic: Annotated[bool, Field(
        default=True,
        description="Include semantic fields with special meaning in Qlik.",
    )] = True
    show_src_tables: Annotated[bool, Field(
        default=True,
        description="Include source table information for each field.",
    )] = True
    show_implicit: Annotated[bool, Field(
        default=True,
        description="Include implicit fields generated by Qlik engine.",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


class GetAppSheetsArgs(BaseModel):
    """Retrieve all sheets from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    creates a SheetList session object, retrieves all sheet metadata,
    and returns the results as structured JSON.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    include_thumbnail: Annotated[bool, Field(
        default=False,
        description="Include base64-encoded sheet thumbnails. Increases response size.",
    )] = False
    include_metadata: Annotated[bool, Field(
        default=True,
        description="Include sheet metadata (title, description, owner, etc.).",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


class GetSheetObjectsArgs(BaseModel):
    """Retrieve all visualization objects from a specific sheet.

    This tool connects to a Qlik Sense server, opens the specified application,
    retrieves the sheet and all its visualization objects with detailed metadata,
    including support for containers and nested objects.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    sheet_id: Annotated[str, Field(
        description="Sheet ID to analyze (GUID format)",
        min_length=1,
        max_length=255,
    )]
    include_properties: Annotated[bool, Field(
        default=True,
        description="Include detailed object properties (colors, settings, etc.).",
    )] = True
    include_layout: Annotated[bool, Field(
        default=True,
        description="Include position and size information for each object.",
    )] = True
    include_data_definition: Annotated[bool, Field(
        default=True,
        description="Include measures and dimensions used in visualizations.",
    )] = True
    resolve_master_items: Annotated[bool, Field(
        default=True,
        description="Resolve Master Item references to show full expressions instead of just IDs.",
    )] = True

    @field_validator("app_id", "sheet_id")
    @classmethod
    def validate_ids(cls, v: str) -> str:
        """Ensure IDs are not empty and properly formatted."""
        if not v.strip():
            raise ValueError("ID cannot be empty or whitespace")
        return v.strip()


class GetAppDimensionsArgs(BaseModel):
    """Retrieve all dimensions from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    retrieves all dimensions with their metadata and configuration details,
    and returns the results as structured JSON for analysis.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    include_title: Annotated[bool, Field(
        default=True,
        description="Include dimension titles for display purposes.",
    )] = True
    include_tags: Annotated[bool, Field(
        default=True,
        description="Include dimension tags for categorization.",
    )] = True
    include_grouping: Annotated[bool, Field(
        default=True,
        description="Include dimension grouping/hierarchy information.",
    )] = True
    include_info: Annotated[bool, Field(
        default=True,
        description="Include detailed dimension metadata and configuration.",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


class ScriptSection(BaseModel):
    """Represents a section/tab in the Qlik script"""

    name: str = Field(description="Section/tab name")
    start_line: int = Field(description="Starting line number")
    end_line: int = Field(description="Ending line number")
    content: str = Field(description="Section content")
    line_count: int = Field(description="Number of lines in section")


class BinaryLoadStatement(BaseModel):
    """Represents a BINARY LOAD statement in the script"""

    line_number: int = Field(description="Line number where statement appears")
    source_app: str = Field(description="Source application path or name")
    full_statement: str = Field(description="Complete BINARY LOAD statement")


class ScriptAnalysis(BaseModel):
    """Analysis and statistics of the script"""

    total_lines: int = Field(description="Total number of lines")
    empty_lines: int = Field(description="Number of empty lines")
    comment_lines: int = Field(description="Number of comment lines")
    sections: list[ScriptSection] = Field(default_factory=list, description="Script sections/tabs")
    load_statements: int = Field(description="Count of LOAD statements")
    store_statements: int = Field(description="Count of STORE statements")
    drop_statements: int = Field(description="Count of DROP statements")
    binary_load_statements: list[BinaryLoadStatement] = Field(
        default_factory=list,
        description="BINARY LOAD statements found",
    )
    set_variables: list[dict[str, Any]] = Field(default_factory=list, description="SET variable declarations")
    let_variables: list[dict[str, Any]] = Field(default_factory=list, description="LET variable declarations")
    connections: list[str] = Field(default_factory=list, description="Connection strings found")
    includes: list[str] = Field(default_factory=list, description="Include/Must_Include files")
    subroutines: list[str] = Field(default_factory=list, description="Subroutine definitions")


class GetAppScriptArgs(BaseModel):
    """Retrieve and optionally analyze the script from a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    retrieves the complete application script used for data loading and transformation,
    optionally performs detailed analysis including BINARY LOAD extraction,
    and returns it as structured JSON.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    analyze_script: Annotated[bool, Field(
        default=False,
        description=(
            "Enable comprehensive script analysis including BINARY LOAD detection, "
            "statement counts, and variable extraction."
        ),
    )] = False
    include_sections: Annotated[bool, Field(
        default=False,
        description="Parse script into sections/tabs based on ///$tab markers.",
    )] = False
    include_line_numbers: Annotated[bool, Field(
        default=False,
        description="Add line numbers to script output for easier reference.",
    )] = False
    max_preview_length: Annotated[int | None, Field(
        default=None,
        description="Maximum characters to return (useful for large scripts). None returns full script.",
        ge=100,
    )] = None

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()

    @field_validator("max_preview_length")
    @classmethod
    def validate_preview_length(cls, v: int | None) -> int | None:
        """Ensure preview length is reasonable if specified."""
        if v is not None and v < 100:
            raise ValueError("max_preview_length must be at least 100 characters if specified")
        return v


class GetAppDataSourcesArgs(BaseModel):
    """Retrieve data sources from a Qlik Sense application's lineage.

    This tool connects to a Qlik Sense server, opens the specified application,
    retrieves the lineage information to identify all data sources used in LOAD
    and STORE statements, and returns categorized results for analysis.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    include_resident: Annotated[bool, Field(
        default=True,
        description="Include RESIDENT data sources (tables loaded from memory).",
    )] = True
    include_file_sources: Annotated[bool, Field(
        default=True,
        description="Include file-based data sources (CSV, Excel, QVD, etc.).",
    )] = True
    include_binary_sources: Annotated[bool, Field(
        default=True,
        description="Include binary data sources (BINARY LOAD from other apps).",
    )] = True
    include_inline_sources: Annotated[bool, Field(
        default=True,
        description="Include inline data sources (data defined directly in script).",
    )] = True

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty and properly formatted."""
        if not v.strip():
            raise ValueError("app_id cannot be empty or whitespace")
        return v.strip()


async def get_app_measures(
    app_id: str,
    include_expression: bool = True,
    include_tags: bool = True,
) -> dict[str, Any]:
    """Retrieve all measures from a Qlik Sense application.

    Args:
        app_id: The Qlik Sense application ID
        include_expression: Whether to include measure expressions
        include_tags: Whether to include measure tags

    Returns:
        JSON object containing measure information

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Sense",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get measures
        result = client.get_measures(
            include_expression=include_expression,
            include_tags=include_tags,
        )

        # Add metadata to response
        response = {
            "app_id": app_id,
            "measures": result["measures"],
            "count": result["count"],
            "retrieved_at": datetime.utcnow().isoformat(),
            "options": {
                "include_expression": include_expression,
                "include_tags": include_tags,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def list_qlik_applications() -> dict[str, Any]:
    """Retrieve a list of all available Qlik Sense applications.

    Returns:
        JSON object containing application list with names and IDs

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik global context
        if not client.connect_global():
            return {
                "error": "Failed to connect to Qlik Sense",
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get application list
        result = client.get_doc_list()

        # Add metadata to response
        response = {
            "applications": result["applications"],
            "count": result["count"],
            "retrieved_at": datetime.utcnow().isoformat(),
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_app_variables(
    app_id: str,
    include_definition: bool = True,
    include_tags: bool = True,
    show_reserved: bool = True,
    show_config: bool = True,
) -> dict[str, Any]:
    """Retrieve all variables from a Qlik Sense application.

    Args:
        app_id: The Qlik Sense application ID
        include_definition: Whether to include variable definitions
        include_tags: Whether to include variable tags
        show_reserved: Whether to include reserved system variables
        show_config: Whether to include configuration variables

    Returns:
        JSON object containing variable information

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Sense",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get variables
        result = client.get_variables(
            include_definition=include_definition,
            include_tags=include_tags,
            show_reserved=show_reserved,
            show_config=show_config,
        )

        # Add metadata to response
        response = {
            "app_id": app_id,
            "variables": result["variables"],
            "count": result["count"],
            "retrieved_at": datetime.utcnow().isoformat(),
            "options": {
                "include_definition": include_definition,
                "include_tags": include_tags,
                "show_reserved": show_reserved,
                "show_config": show_config,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_app_fields(
    app_id: str,
    show_system: bool = True,
    show_hidden: bool = True,
    show_derived_fields: bool = True,
    show_semantic: bool = True,
    show_src_tables: bool = True,
    show_implicit: bool = True,
) -> dict[str, Any]:
    """Retrieve all fields from a Qlik Sense application.

    Args:
        app_id: The Qlik Sense application ID
        show_system: Whether to include system fields
        show_hidden: Whether to include hidden fields
        show_derived_fields: Whether to include derived fields
        show_semantic: Whether to include semantic fields
        show_src_tables: Whether to include source table information
        show_implicit: Whether to include implicit fields

    Returns:
        JSON object containing field information and data model insights

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Sense",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get fields
        result = client.get_fields(
            show_system=show_system,
            show_hidden=show_hidden,
            show_derived_fields=show_derived_fields,
            show_semantic=show_semantic,
            show_src_tables=show_src_tables,
            show_implicit=show_implicit,
        )

        # Add metadata to response
        response = {
            "app_id": app_id,
            "fields": result["fields"],
            "tables": result.get("tables", []),
            "field_count": result["field_count"],
            "table_count": result.get("table_count", 0),
            "retrieved_at": datetime.utcnow().isoformat(),
            "options": {
                "show_system": show_system,
                "show_hidden": show_hidden,
                "show_derived_fields": show_derived_fields,
                "show_semantic": show_semantic,
                "show_src_tables": show_src_tables,
                "show_implicit": show_implicit,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_app_sheets(
    app_id: str,
    include_thumbnail: bool = False,
    include_metadata: bool = True,
) -> dict[str, Any]:
    """Retrieve all sheets from a Qlik Sense application.

    Args:
        app_id: The Qlik Sense application ID
        include_thumbnail: Whether to include sheet thumbnails
        include_metadata: Whether to include sheet metadata

    Returns:
        JSON object containing sheet information

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Sense",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get sheets
        result = client.get_sheets(
            include_thumbnail=include_thumbnail,
            include_metadata=include_metadata,
        )

        # Add metadata to response
        response = {
            "app_id": app_id,
            "sheets": result["sheets"],
            "sheet_count": result["sheet_count"],
            "retrieved_at": datetime.utcnow().isoformat(),
            "options": {
                "include_thumbnail": include_thumbnail,
                "include_metadata": include_metadata,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_sheet_objects(
    app_id: str,
    sheet_id: str,
    include_properties: bool = True,
    include_layout: bool = True,
    include_data_definition: bool = True,
    resolve_master_items: bool = True,
) -> dict[str, Any]:
    """Retrieve all visualization objects from a specific sheet.

    Args:
        app_id: The Qlik Sense application ID
        sheet_id: The sheet ID to analyze
        include_properties: Whether to include object properties
        include_layout: Whether to include position/size info
        include_data_definition: Whether to include measures/dimensions
        resolve_master_items: Whether to resolve Master Item references

    Returns:
        JSON object containing visualization object details

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Sense",
                "app_id": app_id,
                "sheet_id": sheet_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get sheet objects
        result = client.get_sheet_objects(
            sheet_id=sheet_id,
            include_properties=include_properties,
            include_layout=include_layout,
            include_data_definition=include_data_definition,
            resolve_master_items=resolve_master_items,
        )

        # Add metadata to response
        response = {
            "app_id": app_id,
            "sheet_id": sheet_id,
            "sheet_title": result.get("sheet_title", ""),
            "objects": result["objects"],
            "object_count": result["object_count"],
            "retrieved_at": datetime.utcnow().isoformat(),
            "options": {
                "include_properties": include_properties,
                "include_layout": include_layout,
                "include_data_definition": include_data_definition,
                "resolve_master_items": resolve_master_items,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "sheet_id": sheet_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_app_dimensions(
    app_id: str,
    include_title: bool = True,
    include_tags: bool = True,
    include_grouping: bool = True,
    include_info: bool = True,
) -> dict[str, Any]:
    """Retrieve all dimensions from a Qlik Sense application"""
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open the specified app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Engine",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get dimensions from the app
        dimensions_data = client.get_dimensions(
            include_title=include_title,
            include_tags=include_tags,
            include_grouping=include_grouping,
            include_info=include_info,
        )

        # Build response
        response = {
            "app_id": app_id,
            "retrieved_at": datetime.utcnow().isoformat(),
            "dimension_count": dimensions_data["dimension_count"],
            "dimensions": dimensions_data["dimensions"],
            "options": {
                "include_title": include_title,
                "include_tags": include_tags,
                "include_grouping": include_grouping,
                "include_info": include_info,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


def parse_script_sections(script: str) -> list[ScriptSection]:
    """Parse script into sections/tabs based on ///$tab markers"""
    sections = []
    lines = script.split("\n")
    current_section = None
    current_content = []
    current_start = 0

    for i, line in enumerate(lines, 1):
        if line.strip().startswith("///$tab"):
            # Save previous section if exists
            if current_section:
                sections.append(ScriptSection(
                    name=current_section,
                    start_line=current_start,
                    end_line=i - 1,
                    content="\n".join(current_content),
                    line_count=len(current_content),
                ))

            # Start new section
            parts = line.strip().split(None, 1)
            current_section = parts[1] if len(parts) > 1 else f"Section_{len(sections) + 1}"
            current_content = []
            current_start = i + 1
        elif current_section is not None:
            current_content.append(line)

    # Save last section
    if current_section and current_content:
        sections.append(ScriptSection(
            name=current_section,
            start_line=current_start,
            end_line=len(lines),
            content="\n".join(current_content),
            line_count=len(current_content),
        ))

    # If no sections found, treat entire script as one section
    if not sections and script.strip():
        sections.append(ScriptSection(
            name="Main",
            start_line=1,
            end_line=len(lines),
            content=script,
            line_count=len(lines),
        ))

    return sections


def extract_binary_load_statements(script: str) -> list[BinaryLoadStatement]:
    """Extract BINARY LOAD statements from the script"""
    binary_loads = []
    lines = script.split("\n")

    # Pattern to match BINARY LOAD statements (case-insensitive)
    # Matches: BINARY [path];  or  BINARY LOAD FROM [path];
    binary_pattern = re.compile(
        r"^\s*BINARY\s+(?:LOAD\s+FROM\s+)?([^;]+);?\s*$",
        re.IGNORECASE | re.MULTILINE,
    )

    for i, line in enumerate(lines, 1):
        match = binary_pattern.match(line)
        if match:
            # Clean up the source app path - remove quotes, brackets, and whitespace
            source_app = match.group(1).strip()
            # Remove surrounding brackets if present
            if source_app.startswith("[") and source_app.endswith("]"):
                source_app = source_app[1:-1]
            # Remove surrounding quotes
            source_app = source_app.strip('"').strip("'")

            binary_loads.append(BinaryLoadStatement(
                line_number=i,
                source_app=source_app,
                full_statement=line.strip(),
            ))

    return binary_loads


def perform_script_analysis(script: str, include_sections: bool = False) -> ScriptAnalysis:
    """Perform comprehensive analysis of the Qlik script"""
    lines = script.split("\n")

    # Initialize counters
    empty_lines = sum(1 for line in lines if not line.strip())
    comment_lines = sum(1 for line in lines if line.strip().startswith("//") or line.strip().startswith("/*"))

    # Parse sections if requested
    sections = parse_script_sections(script) if include_sections else []

    # Extract BINARY LOAD statements
    binary_loads = extract_binary_load_statements(script)

    # Count statement types (case-insensitive)
    script_upper = script.upper()
    load_statements = len(re.findall(r"\bLOAD\b", script_upper))
    store_statements = len(re.findall(r"\bSTORE\b", script_upper))
    drop_statements = len(re.findall(r"\bDROP\b", script_upper))

    # Extract SET and LET variables
    set_pattern = re.compile(r"^\s*SET\s+(\w+)\s*=\s*(.+?);?\s*$", re.IGNORECASE | re.MULTILINE)
    let_pattern = re.compile(r"^\s*LET\s+(\w+)\s*=\s*(.+?);?\s*$", re.IGNORECASE | re.MULTILINE)

    set_variables = []
    for match in set_pattern.finditer(script):
        set_variables.append({
            "name": match.group(1),
            "value": match.group(2).strip(),
            "line": script[:match.start()].count("\n") + 1,
        })

    let_variables = []
    for match in let_pattern.finditer(script):
        let_variables.append({
            "name": match.group(1),
            "value": match.group(2).strip(),
            "line": script[:match.start()].count("\n") + 1,
        })

    # Extract connection strings (simplified - matches CONNECT TO statements)
    connection_pattern = re.compile(r"^\s*(?:LIB\s+)?CONNECT\s+TO\s+(.+?);?\s*$", re.IGNORECASE | re.MULTILINE)
    connections = [match.group(1).strip().strip('"').strip("'") for match in connection_pattern.finditer(script)]

    # Extract includes
    include_pattern = re.compile(r"^\s*\$\((?:Must_)?Include\s*=\s*(.+?)\);?\s*$", re.IGNORECASE | re.MULTILINE)
    includes = [match.group(1).strip().strip('"').strip("'") for match in include_pattern.finditer(script)]

    # Extract subroutines
    sub_pattern = re.compile(r"^\s*SUB\s+(\w+)", re.IGNORECASE | re.MULTILINE)
    subroutines = [match.group(1) for match in sub_pattern.finditer(script)]

    return ScriptAnalysis(
        total_lines=len(lines),
        empty_lines=empty_lines,
        comment_lines=comment_lines,
        sections=sections,
        load_statements=load_statements,
        store_statements=store_statements,
        drop_statements=drop_statements,
        binary_load_statements=binary_loads,
        set_variables=set_variables,
        let_variables=let_variables,
        connections=connections,
        includes=includes,
        subroutines=subroutines,
    )


def add_line_numbers(script: str) -> str:
    """Add line numbers to script content"""
    lines = script.split("\n")
    numbered_lines = []
    max_line_num = len(lines)
    padding = len(str(max_line_num))

    for i, line in enumerate(lines, 1):
        numbered_lines.append(f"{i:>{padding}}: {line}")

    return "\n".join(numbered_lines)


def sanitize_script(script: str) -> str:
    """Sanitize sensitive information from script"""
    # Mask passwords in connection strings
    script = re.sub(
        r'(PASSWORD\s*=\s*)[\'"]?[^\'";\s]+[\'"]?',
        r"\1[MASKED]",
        script,
        flags=re.IGNORECASE,
    )

    # Mask user credentials
    script = re.sub(
        r'(USER\s+ID\s*=\s*)[\'"]?[^\'";\s]+[\'"]?',
        r"\1[MASKED]",
        script,
        flags=re.IGNORECASE,
    )

    return script


async def get_app_script(
    app_id: str,
    analyze_script: bool = False,
    include_sections: bool = False,
    include_line_numbers: bool = False,
    max_preview_length: int | None = None,
) -> dict[str, Any]:
    """Retrieve and optionally analyze the script from a Qlik Sense application.

    Args:
        app_id: The Qlik Sense application ID
        analyze_script: Enable detailed script analysis and parsing
        include_sections: Parse and return script sections/tabs
        include_line_numbers: Add line numbers to script output
        max_preview_length: Maximum characters to return for script preview

    Returns:
        JSON object containing script content and optional analysis

    """
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open the specified app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Engine",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get script from the app
        script_data = client.get_script()

        if "error" in script_data:
            return {
                "error": script_data["error"],
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        script_content = script_data["script"]

        # Sanitize sensitive information
        script_content = sanitize_script(script_content)

        # Apply preview length limit if specified
        original_length = len(script_content)
        if max_preview_length and len(script_content) > max_preview_length:
            script_content = script_content[:max_preview_length]
            is_truncated = True
        else:
            is_truncated = False

        # Add line numbers if requested
        if include_line_numbers:
            script_content = add_line_numbers(script_content)

        # Build response
        response = {
            "app_id": app_id,
            "retrieved_at": datetime.utcnow().isoformat(),
            "script": script_content,
            "script_length": original_length,
            "is_truncated": is_truncated,
        }

        # Add truncation info if applicable
        if is_truncated:
            response["truncated_at"] = max_preview_length
            response["truncation_note"] = (
                f"Script truncated to {max_preview_length:,} characters "
                f"(original: {original_length:,} characters)"
            )

        # Perform analysis if requested
        if analyze_script or include_sections:
            analysis_result = perform_script_analysis(script_data["script"], include_sections=include_sections)

            # Convert Pydantic models to dict for JSON serialization
            if hasattr(analysis_result, "model_dump"):
                analysis_dict = analysis_result.model_dump()
            else:
                analysis_dict = analysis_result.dict()

            # Add analysis to response
            response["analysis"] = analysis_dict

            # Add summary statistics
            response["summary"] = {
                "total_lines": analysis_result.total_lines,
                "sections_count": len(analysis_result.sections),
                "load_statements": analysis_result.load_statements,
                "store_statements": analysis_result.store_statements,
                "binary_load_count": len(analysis_result.binary_load_statements),
                "variables_count": len(analysis_result.set_variables) + len(analysis_result.let_variables),
                "connections_count": len(analysis_result.connections),
                "subroutines_count": len(analysis_result.subroutines),
            }

        # Add sections separately if requested (for easier access)
        if include_sections and not analyze_script:
            sections = parse_script_sections(script_data["script"])
            response["sections"] = [section.dict() for section in sections]
            response["sections_count"] = len(sections)

        return response

    except Exception as e:
        import traceback
        return {
            "error": str(e),
            "error_type": type(e).__name__,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
            "traceback": traceback.format_exc(),
        }

    finally:
        # Always disconnect
        client.disconnect()


async def get_app_data_sources(
    app_id: str,
    include_resident: bool = True,
    include_file_sources: bool = True,
    include_binary_sources: bool = True,
    include_inline_sources: bool = True,
) -> dict[str, Any]:
    """Retrieve data sources from a Qlik Sense application's lineage"""
    from .qlik_client import QlikClient

    client = QlikClient()

    try:
        # Connect to Qlik and open the specified app
        if not client.connect(app_id):
            return {
                "error": "Failed to connect to Qlik Engine",
                "app_id": app_id,
                "timestamp": datetime.utcnow().isoformat(),
            }

        # Get lineage data from the app
        lineage_data = client.get_lineage(
            include_resident=include_resident,
            include_file_sources=include_file_sources,
            include_binary_sources=include_binary_sources,
            include_inline_sources=include_inline_sources,
        )

        # Build response
        response = {
            "app_id": app_id,
            "retrieved_at": datetime.utcnow().isoformat(),
            "source_count": lineage_data["source_count"],
            "data_sources": lineage_data["data_sources"],
            "categories": lineage_data["categories"],
            "by_category": lineage_data["by_category"],
            "options": {
                "include_resident": include_resident,
                "include_file_sources": include_file_sources,
                "include_binary_sources": include_binary_sources,
                "include_inline_sources": include_inline_sources,
            },
        }

        return response

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        # Always disconnect
        client.disconnect()


# ============================================
# WRITE Tools
# ============================================


class CreateMeasureArgs(BaseModel):
    """Create a new master measure in a Qlik Sense application.

    This tool connects to a Qlik Sense server, opens the specified application,
    creates a new master measure with the provided properties, and returns
    the result of the operation.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    title: Annotated[str, Field(
        description="Measure title/name",
        min_length=1,
        max_length=255,
    )]
    expression: Annotated[str, Field(
        description="Qlik expression (e.g., 'Sum(Sales)', 'Count(Distinct CustomerID)')",
        min_length=1,
    )]
    description: Annotated[str, Field(
        default="",
        description="Optional description for the measure",
    )] = ""
    label: Annotated[str, Field(
        default="",
        description="Optional display label (defaults to title if not provided)",
    )] = ""
    tags: Annotated[list[str] | None, Field(
        default=None,
        description="Optional list of tags for categorization",
    )] = None

    @field_validator("app_id", "title", "expression")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class CreateVariableArgs(BaseModel):
    """Create a new variable in a Qlik Sense application.

    Variables can hold static values or dynamic expressions and can be
    used throughout the app in expressions and scripts.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    name: Annotated[str, Field(
        description="Variable name (case sensitive)",
        min_length=1,
        max_length=255,
    )]
    definition: Annotated[str, Field(
        default="",
        description="Variable value or expression",
    )] = ""
    comment: Annotated[str, Field(
        default="",
        description="Optional comment/description",
    )] = ""

    @field_validator("app_id", "name")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class CreateDimensionArgs(BaseModel):
    """Create a new master dimension in a Qlik Sense application.

    Master dimensions are stored in the library and can be reused
    across multiple visualizations in the app.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    title: Annotated[str, Field(
        description="Dimension title/name",
        min_length=1,
        max_length=255,
    )]
    field_def: Annotated[str | list[str], Field(
        description="Field name(s) - string for single field, list for drill-down hierarchy",
    )]
    description: Annotated[str, Field(
        default="",
        description="Optional description",
    )] = ""
    tags: Annotated[list[str] | None, Field(
        default=None,
        description="Optional list of tags",
    )] = None
    grouping: Annotated[str, Field(
        default="N",
        description="Grouping type: 'N' for None (flat), 'H' for Drill-down hierarchy",
    )] = "N"

    @field_validator("app_id", "title")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()

    @field_validator("grouping")
    @classmethod
    def validate_grouping(cls, v: str) -> str:
        """Ensure grouping is valid."""
        if v not in ("N", "H"):
            raise ValueError("grouping must be 'N' or 'H'")
        return v


class CreateSheetArgs(BaseModel):
    """Create a new sheet in a Qlik Sense application.

    Sheets are containers for visualizations and other objects.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    title: Annotated[str, Field(
        description="Sheet title",
        min_length=1,
        max_length=255,
    )]
    description: Annotated[str, Field(
        default="",
        description="Optional sheet description",
    )] = ""

    @field_validator("app_id", "title")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class CreateObjectArgs(BaseModel):
    """Create a generic object (visualization) in a Qlik Sense application.

    This is a low-level tool for creating any type of Qlik object including
    charts, tables, KPIs, and custom visualizations.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    object_type: Annotated[str, Field(
        description="Type of object: 'barchart', 'linechart', 'piechart', 'table', 'kpi', 'map', etc.",
        min_length=1,
    )]
    title: Annotated[str, Field(
        description="Object title",
        min_length=1,
        max_length=255,
    )]
    properties: Annotated[dict[str, Any] | None, Field(
        default=None,
        description="Object-specific properties (dimensions, measures, etc.)",
    )] = None

    @field_validator("app_id", "object_type", "title")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()



class UpdateMeasureArgs(BaseModel):
    """Update an existing master measure in a Qlik Sense application."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    measure_id: Annotated[str, Field(
        description="Existing measure ID (qId)",
        min_length=1,
        max_length=255,
    )]
    title: Annotated[str | None, Field(
        default=None,
        description="Optional new title for the measure",
    )] = None
    expression: Annotated[str | None, Field(
        default=None,
        description="Optional new expression",
    )] = None
    description: Annotated[str | None, Field(
        default=None,
        description="Optional new description",
    )] = None
    label: Annotated[str | None, Field(
        default=None,
        description="Optional label override",
    )] = None
    tags: Annotated[list[str] | None, Field(
        default=None,
        description="Optional tag list",
    )] = None

    @field_validator("app_id", "measure_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class DeleteMeasureArgs(BaseModel):
    """Delete an existing master measure."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    measure_id: Annotated[str, Field(
        description="Measure ID (qId)",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id", "measure_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class UpdateVariableArgs(BaseModel):
    """Update the definition of an existing variable."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    name: Annotated[str, Field(
        description="Variable name",
        min_length=1,
        max_length=255,
    )]
    definition: Annotated[str | None, Field(
        default=None,
        description="New definition/value",
    )] = None

    @field_validator("app_id", "name")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class DeleteVariableArgs(BaseModel):
    """Delete a variable from an application."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    name: Annotated[str, Field(
        description="Variable name",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id", "name")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class UpdateDimensionArgs(BaseModel):
    """Update a master dimension."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    dimension_id: Annotated[str, Field(
        description="Dimension ID (qId)",
        min_length=1,
        max_length=255,
    )]
    title: Annotated[str | None, Field(
        default=None,
        description="Optional new title",
    )] = None
    field_def: Annotated[str | list[str] | None, Field(
        default=None,
        description="Optional field(s) used by the dimension",
    )] = None
    description: Annotated[str | None, Field(
        default=None,
        description="Optional description",
    )] = None
    tags: Annotated[list[str] | None, Field(
        default=None,
        description="Optional tag list",
    )] = None
    grouping: Annotated[str | None, Field(
        default=None,
        description="Optional grouping ('N' or 'H')",
    )] = None

    @field_validator("app_id", "dimension_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()

    @field_validator("grouping")
    @classmethod
    def _validate_grouping(cls, v: str | None) -> str | None:
        if v is not None and v not in ("N", "H"):
            raise ValueError("grouping must be 'N' or 'H'")
        return v


class DeleteDimensionArgs(BaseModel):
    """Delete a master dimension."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    dimension_id: Annotated[str, Field(
        description="Dimension ID (qId)",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id", "dimension_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class AddObjectToSheetArgs(BaseModel):
    """Add an existing object to a sheet with positioning hints."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    sheet_id: Annotated[str, Field(
        description="Sheet ID where the object should land",
        min_length=1,
        max_length=255,
    )]
    object_id: Annotated[str, Field(
        description="Object ID (qId) to place",
        min_length=1,
        max_length=255,
    )]
    column: Annotated[int, Field(
        default=0,
        description="Column position on the sheet (0-indexed)",
        ge=0,
    )] = 0
    row: Annotated[int, Field(
        default=0,
        description="Row position on the sheet (0-indexed)",
        ge=0,
    )] = 0
    colspan: Annotated[int, Field(
        default=6,
        description="Column span the object should occupy",
        ge=1,
    )] = 6
    rowspan: Annotated[int, Field(
        default=6,
        description="Row span the object should occupy",
        ge=1,
    )] = 6

    @field_validator("app_id", "sheet_id", "object_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class GetSheetLayoutArgs(BaseModel):
    """Read the current layout grid for a sheet and its placed objects."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    sheet_id: Annotated[str, Field(
        description="Sheet ID to inspect",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id", "sheet_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class RepositionSheetObjectArgs(BaseModel):
    """Move or resize an object already placed on a Qlik Sense sheet."""

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID",
        min_length=1,
        max_length=255,
    )]
    sheet_id: Annotated[str, Field(
        description="Sheet ID containing the object",
        min_length=1,
        max_length=255,
    )]
    object_id: Annotated[str, Field(
        description="Object ID (qId) already placed on the sheet",
        min_length=1,
        max_length=255,
    )]
    column: Annotated[int, Field(
        description="New column position on the sheet (0-indexed)",
        ge=0,
    )]
    row: Annotated[int, Field(
        description="New row position on the sheet (0-indexed)",
        ge=0,
    )]
    colspan: Annotated[int, Field(
        default=6,
        description="Updated column span for the object",
        ge=1,
    )] = 6
    rowspan: Annotated[int, Field(
        default=6,
        description="Updated row span for the object",
        ge=1,
    )] = 6

    @field_validator("app_id", "sheet_id", "object_id")
    @classmethod
    def _validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class SetScriptArgs(BaseModel):
    """Set the data load script for a Qlik Sense application.

    WARNING: This replaces the entire script. Use get_app_script first
    to retrieve the current script if you want to modify it.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]
    script: Annotated[str, Field(
        description="Complete load script content",
        min_length=1,
    )]

    @field_validator("app_id", "script")
    @classmethod
    def validate_required(cls, v: str) -> str:
        """Ensure required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class SaveAppArgs(BaseModel):
    """Save a Qlik Sense application.

    Saves all changes made to the app since the last save or since it was opened.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty."""
        if not v or not v.strip():
            raise ValueError("app_id cannot be empty")
        return v.strip()


class ReloadAppArgs(BaseModel):
    """Trigger a data reload for a Qlik Sense application.

    This reloads all data according to the load script.
    Depending on data volume, this may take a long time.
    """

    app_id: Annotated[str, Field(
        description="Qlik Sense application ID (GUID format or app name)",
        min_length=1,
        max_length=255,
    )]

    @field_validator("app_id")
    @classmethod
    def validate_app_id(cls, v: str) -> str:
        """Ensure app_id is not empty."""
        if not v or not v.strip():
            raise ValueError("app_id cannot be empty")
        return v.strip()


async def create_measure(
    app_id: str,
    title: str,
    expression: str,
    description: str = "",
    label: str = "",
    tags: list[str] | None = None,
) -> dict[str, Any]:
    """Create a new master measure in a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.create_measure(
            title=title,
            expression=expression,
            description=description,
            label=label,
            tags=tags,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def create_variable(
    app_id: str,
    name: str,
    definition: str = "",
    comment: str = "",
) -> dict[str, Any]:
    """Create a new variable in a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.create_variable(
            name=name,
            definition=definition,
            comment=comment,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def create_dimension(
    app_id: str,
    title: str,
    field_def: str | list[str],
    description: str = "",
    tags: list[str] | None = None,
    grouping: str = "N",
) -> dict[str, Any]:
    """Create a new master dimension in a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.create_dimension(
            title=title,
            field_def=field_def,
            description=description,
            tags=tags,
            grouping=grouping,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def create_sheet(
    app_id: str,
    title: str,
    description: str = "",
) -> dict[str, Any]:
    """Create a new sheet in a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.create_sheet(
            title=title,
            description=description,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def create_object(
    app_id: str,
    object_type: str,
    title: str,
    properties: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Create a generic object (visualization) in a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.create_object(
            object_type=object_type,
            title=title,
            properties=properties,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def update_measure(
    app_id: str,
    measure_id: str,
    title: str | None = None,
    expression: str | None = None,
    description: str | None = None,
    label: str | None = None,
    tags: list[str] | None = None,
) -> dict[str, Any]:
    """Update a master measure inside a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.update_measure(
            measure_id=measure_id,
            title=title,
            expression=expression,
            description=description,
            label=label,
            tags=tags,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def delete_measure(
    app_id: str,
    measure_id: str,
) -> dict[str, Any]:
    """Delete a master measure from a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.delete_measure(measure_id=measure_id)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def update_variable(
    app_id: str,
    name: str,
    definition: str | None = None,
) -> dict[str, Any]:
    """Update a variable definition."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.update_variable(name=name, definition=definition)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def delete_variable(
    app_id: str,
    name: str,
) -> dict[str, Any]:
    """Delete a variable from the application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.delete_variable(name=name)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def update_dimension(
    app_id: str,
    dimension_id: str,
    title: str | None = None,
    field_def: str | list[str] | None = None,
    description: str | None = None,
    tags: list[str] | None = None,
    grouping: str | None = None,
) -> dict[str, Any]:
    """Update a master dimension."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.update_dimension(
            dimension_id=dimension_id,
            title=title,
            field_def=field_def,
            description=description,
            tags=tags,
            grouping=grouping,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def delete_dimension(
    app_id: str,
    dimension_id: str,
) -> dict[str, Any]:
    """Delete a master dimension."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.delete_dimension(dimension_id=dimension_id)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def add_object_to_sheet(
    app_id: str,
    sheet_id: str,
    object_id: str,
    column: int = 0,
    row: int = 0,
    colspan: int = 6,
    rowspan: int = 6,
) -> dict[str, Any]:
    """Place an existing object onto the requested sheet."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.add_object_to_sheet(
            sheet_id=sheet_id,
            object_id=object_id,
            col=column,
            row=row,
            colspan=colspan,
            rowspan=rowspan,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def get_sheet_layout(
    app_id: str,
    sheet_id: str,
) -> dict[str, Any]:
    """Read sheet grid layout and object placements."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.get_sheet_layout(sheet_id=sheet_id)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def reposition_sheet_object(
    app_id: str,
    sheet_id: str,
    object_id: str,
    column: int,
    row: int,
    colspan: int = 6,
    rowspan: int = 6,
) -> dict[str, Any]:
    """Move or resize an object already placed on a sheet."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.reposition_sheet_object(
            sheet_id=sheet_id,
            object_id=object_id,
            col=column,
            row=row,
            colspan=colspan,
            rowspan=rowspan,
        )

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def set_script(
    app_id: str,
    script: str,
) -> dict[str, Any]:
    """Set the data load script for a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.set_script(script=script)

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def save_app(app_id: str) -> dict[str, Any]:
    """Save a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.save_app()

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()


async def reload_app(app_id: str) -> dict[str, Any]:
    """Trigger a data reload for a Qlik Sense application."""
    client = QlikClient()

    try:
        if not client.connect(app_id):
            return {"error": f"Failed to connect to app: {app_id}"}

        result = client.do_reload()

        return {
            **result,
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        return {
            "error": str(e),
            "app_id": app_id,
            "timestamp": datetime.utcnow().isoformat(),
        }

    finally:
        client.disconnect()
